const gearOptions = {
  helmet: {
    categories: [
      {
        name: "Soldier",
        image: "T3_HEAD_CLOTH_SET1",
        items: [
          { id: "T8_HEAD_CLOTH_SET1", name: "Scholar Cowl" },
          { id: "T8_HEAD_CLOTH_SET2", name: "Cleric Cowl" },
          { id: "T8_HEAD_CLOTH_SET3", name: "Mage Cowl" },
          { id: "T8_HEAD_CLOTH_ROYAL", name: "Royal Cowl" },
          { id: "T8_HEAD_CLOTH_KEEPER", name: "Druid Cowl" },
          { id: "T8_HEAD_CLOTH_HELL", name: "Fiend Cowl" },
          { id: "T8_HEAD_CLOTH_MORGANA", name: "Cultist Cowl" },
          { id: "T8_HEAD_CLOTH_FEY", name: "Feyscale Cowl" },
          { id: "T8_HEAD_CLOTH_AVALON", name: "Avalonian Cowl" },
        ],
      },
      {
        name: "Hunter",
        image: "T3_HEAD_LEATHER_SET1",
        items: [
          { id: "T8_HEAD_LEATHER_SET1", name: "Mercenary Hood" },
          { id: "T8_HEAD_LEATHER_SET2", name: "Hunter Hood" },
          { id: "T8_HEAD_LEATHER_SET3", name: "Assassin Hood" },
          { id: "T8_HEAD_LEATHER_ROYAL", name: "Royal Hood" },
          { id: "T8_HEAD_LEATHER_MORGANA", name: "Stalker Hood" },
          { id: "T8_HEAD_LEATHER_HELL", name: "Hellion Hood" },
          { id: "T8_HEAD_LEATHER_UNDEAD", name: "Specter Hood" },
          { id: "T8_HEAD_LEATHER_FEY", name: "Feyscale Hood" },
          { id: "T8_HEAD_LEATHER_AVALON", name: "Avalonian Hood" },
        ],
      },
      {
        name: "Mage",
        image: "T3_HEAD_PLATE_SET1",
        items: [
          { id: "T8_HEAD_PLATE_SET1", name: "Guardian Helmet" },
          { id: "T8_HEAD_PLATE_SET2", name: "Soldier Helmet" },
          { id: "T8_HEAD_PLATE_SET3", name: "Knight Helmet" },
          { id: "T8_HEAD_PLATE_ROYAL", name: "Royal Helmet" },
          { id: "T8_HEAD_PLATE_UNDEAD", name: "Graveguard Helmet" },
          { id: "T8_HEAD_PLATE_HELL", name: "Demon Helmet" },
          { id: "T8_HEAD_PLATE_KEEPER", name: "Judicator Helmet" },
          { id: "T8_HEAD_PLATE_FEY", name: "Feyscale Helmet" },
          { id: "T8_HEAD_PLATE_AVALON", name: "Avalonian Helmet" },
        ],
      },
    ],
  },

  cape: {
    items: [
      { id: "T8_CAPE", name: "Standard Cape" },
      { id: "T8_CAPEITEM_FW_BRIDGEWATCH", name: "Bridgewatch Cape" },
      { id: "T8_CAPEITEM_FW_FORTSTERLING", name: "Fort Sterling Cape" },
      { id: "T8_CAPEITEM_FW_LYMHURST", name: "Lymhurst Cape" },
      { id: "T8_CAPEITEM_FW_MARTLOCK", name: "Martlock Cape" },
      { id: "T8_CAPEITEM_FW_THETFORD", name: "Thetford Cape" },
      { id: "T8_CAPEITEM_FW_CAERLEON", name: "Caerleon Cape" },
      { id: "T8_CAPEITEM_FW_BRECILIEN", name: "Brecilien Cape" },
      { id: "T8_CAPEITEM_AVALON", name: "Avalonian Cape" },
      { id: "T8_CAPEITEM_SMUGGLER", name: "Smuggler Cape" },
      { id: "T8_CAPEITEM_HERETIC", name: "Heretic Cape" },
      { id: "T8_CAPEITEM_UNDEAD", name: "Undead Cape" },
      { id: "T8_CAPEITEM_KEEPER", name: "Keeper Cape" },
      { id: "T8_CAPEITEM_MORGANA", name: "Morgana Cape" },
      { id: "T8_CAPEITEM_DEMON", name: "Demon Cape" },
    ],
  },

  potion: {
    items: [
      { id: "T6_POTION_HEAL", name: "Healing Potion" },
      { id: "T6_POTION_ENERGY", name: "Energy Potion" },
      { id: "T7_POTION_REVIVE", name: "Resurrection Potion" },
      { id: "T7_POTION_STONESKIN", name: "Gigantify Potion" },
      { id: "T7_POTION_SLOWFIELD", name: "Sticky Potion" },
      { id: "T8_POTION_COOLDOWN", name: "Cooldown Reduction Potion" },
      { id: "T8_POTION_CLEANSE", name: "Major Resistance Potion" },
      { id: "T7_POTION_MOB_RESET", name: "Invisibility Potion" },
      { id: "T7_POTION_CLEANSE2", name: "Poison Antidote Potion" },
      { id: "T7_POTION_ACID", name: "Acid Potion" },
      { id: "T8_POTION_BERSERK", name: "Fury Potion" },
      { id: "T8_POTION_LAVA", name: "Sticky Lava Potion" },
      { id: "T8_POTION_GATHER", name: "Harvesting Potion" },
      { id: "T8_POTION_TORNADO", name: "Tornado Potion" },
    ],
  },

  food: {
    items: [
      { id: "T5_MEAL_SOUP", name: "Carrot Soup" },
      { id: "T5_MEAL_SOUP_FISH", name: "Fish Soup" },
      { id: "T6_MEAL_SALAD", name: "Bean Salad" },
      { id: "T6_MEAL_SALAD_FISH", name: "Fish Salad" },
      { id: "T7_MEAL_PIE", name: "Goose Pie" },
      { id: "T7_MEAL_PIE_FISH", name: "Fish Pie" },
      { id: "T7_MEAL_OMELETTE", name: "Pork Omelette" },
      { id: "T7_MEAL_OMELETTE_FISH", name: "Fish Omelette" },
      { id: "T7_MEAL_OMELETTE_AVALON", name: "Avalonian Omelette" },
      { id: "T8_MEAL_STEW", name: "Beef Stew" },
      { id: "T8_MEAL_STEW_FISH", name: "Fish Stew" },
      { id: "T8_MEAL_STEW_AVALON", name: "Avalonian Stew" },
      { id: "T8_MEAL_SANDWICH", name: "Mutton Sandwich" },
      { id: "T8_MEAL_SANDWICH_FISH", name: "Fish Sandwich" },
      { id: "T8_MEAL_SANDWICH_AVALON", name: "Avalonian Sandwich" },
      { id: "T7_MEAL_ROAST", name: "Roast Pork" },
      { id: "T7_MEAL_ROAST_FISH", name: "Fish Roast" },
      {
        id: "T7_FISH_FRESHWATER_ALL_COMMON",
        name: "T7 Common Freshwater Fish",
      },
      {
        id: "T8_FISH_FRESHWATER_ALL_COMMON",
        name: "T8 Common Freshwater Fish",
      },
      { id: "T7_FISH_SALTWATER_ALL_COMMON", name: "T7 Common Saltwater Fish" },
      { id: "T8_FISH_SALTWATER_ALL_COMMON", name: "T8 Common Saltwater Fish" },
      { id: "T7_FISH_FRESHWATER_FOREST_RARE", name: "T7 Rare Forest Fish" },
      { id: "T7_FISH_FRESHWATER_MOUNTAIN_RARE", name: "T7 Rare Mountain Fish" },
      {
        id: "T7_FISH_FRESHWATER_HIGHLANDS_RARE",
        name: "T7 Rare Highlands Fish",
      },
      { id: "T7_FISH_FRESHWATER_STEPPE_RARE", name: "T7 Rare Steppe Fish" },
      { id: "T7_FISH_FRESHWATER_SWAMP_RARE", name: "T7 Rare Swamp Fish" },
      { id: "T7_FISH_SALTWATER_ALL_RARE", name: "T7 Rare Saltwater Fish" },
      { id: "T7_FISH_FRESHWATER_AVALON_RARE", name: "T7 Avalonian Fish" },
    ],
  },

  mount: {
    items: [
      { id: "T8_MOUNT_HORSE", name: "Tier 8 Horse" },
      { id: "T8_MOUNT_ARMORED_HORSE", name: "Tier 8 Armored Horse" },
      { id: "T8_MOUNT_OX", name: "Tier 8 Ox" },
      { id: "T4_MOUNT_GIANTSTAG", name: "Giant Stag" },
      { id: "T5_MOUNT_COUGAR_KEEPER", name: "Swiftclaw" },
      { id: "T6_MOUNT_GIANTSTAG_MOOSE", name: "Moose" },
      { id: "T6_MOUNT_DIREWOLF", name: "Direwolf" },
      { id: "T7_MOUNT_DIREBOAR", name: "Direboar" },
      { id: "T7_MOUNT_SWAMPDRAGON", name: "Terrorbird" },
      { id: "T7_MOUNT_SWAMPDRAGON_AVALON_BASILISK", name: "Basilisk" },
      { id: "T8_MOUNT_DIREBEAR", name: "Direbear" },
      { id: "T8_MOUNT_MAMMOTH_TRANSPORT", name: "Transport Mammoth" },
      { id: "T8_MOUNT_HORSE_UNDEAD", name: "Spectral Bonehorse" },
      { id: "T8_MOUNT_COUGAR_KEEPER", name: "Rageclaw" },
      { id: "T8_MOUNT_ARMORED_HORSE_MORGANA", name: "Nightmare" },
      { id: "T8_MOUNT_RABBIT_EASTER", name: "White Bunny" },
      { id: "T8_MOUNT_RABBIT_EASTER_DARK", name: "Dark Bunny" },
      { id: "UNIQUE_MOUNT_DIVINE_OWL_ADC", name: "Divine Owl" },
      { id: "T6_MOUNT_FROSTRAM_ADC", name: "Frost Ram" },
      { id: "UNIQUE_MOUNT_HERETIC_MULE_ADC", name: "Heretic Combat Mule" },
      { id: "UNIQUE_MOUNT_MORGANA_RAVEN_ADC", name: "Morgana Raven" },
      { id: "UNIQUE_MOUNT_GIANT_HORSE_ADC", name: "Giant Horse" },
      { id: "UNIQUE_MOUNT_BEAR_KEEPER_ADC", name: "Keeper Bear" },
      { id: "T7_MOUNT_MONITORLIZARD_ADC", name: "Monitor Lizard" },
      { id: "T7_MOUNT_HUSKY_ADC", name: "Direwolf Husky" },
      { id: "UNIQUE_MOUNT_BAT_PERSONAL", name: "Bat Mount" },
      { id: "UNIQUE_MOUNT_UNDEAD_DIREBOAR_ADC", name: "Undead Boar" },
      { id: "T7_MOUNT_TERRORBIRD_ADC", name: "Terrorbird (Skin)" },
      { id: "UNIQUE_MOUNT_BLACK_PANTHER_ADC", name: "Black Panther" },
      {
        id: "T8_MOUNT_MOABIRD_FW_BRIDGEWATCH_ELITE",
        name: "Elite Moabird – Bridgewatch",
      },
      {
        id: "T8_MOUNT_DIREBEAR_FW_FORTSTERLING_ELITE",
        name: "Elite Direbear – Fort Sterling",
      },
      {
        id: "T8_MOUNT_DIREBOAR_FW_LYMHURST_ELITE",
        name: "Elite Direboar – Lymhurst",
      },
      { id: "T8_MOUNT_RAM_FW_MARTLOCK_ELITE", name: "Elite Ram – Martlock" },
      {
        id: "T8_MOUNT_SWAMPDRAGON_FW_THETFORD_ELITE",
        name: "Elite Swamp Dragon – Thetford",
      },
      {
        id: "T8_MOUNT_GREYWOLF_FW_CAERLEON_ELITE",
        name: "Elite Greywolf – Caerleon",
      },
      { id: "T8_MOUNT_OWL_FW_BRECILIEN_ELITE", name: "Elite Owl – Brecilien" },
      { id: "T6_MOUNT_SIEGE_BALLISTA", name: "Siege Ballista" },
      { id: "T7_MOUNT_SWAMPDRAGON_BATTLE", name: "Battle Mount: Lizard" },
      { id: "T8_MOUNT_MAMMOTH_BATTLE", name: "Battle Mount: Mammoth" },
      { id: "T8_MOUNT_ARMORED_HORSE_SKIN_01", name: "Armored Horse Skin" },
      { id: "UNIQUE_MOUNT_RHINO_SEASON_CRYSTAL", name: "Crystal Rhino" },
      {
        id: "UNIQUE_MOUNT_TOWER_CHARIOT_CRYSTAL",
        name: "Crystal Tower Chariot",
      },
      {
        id: "UNIQUE_MOUNT_ARMORED_EAGLE_CRYSTAL",
        name: "Crystal Armored Eagle",
      },
      { id: "UNIQUE_MOUNT_BEETLE_CRYSTAL", name: "Crystal Beetle" },
      { id: "UNIQUE_MOUNT_BEHEMOTH_CRYSTAL", name: "Crystal Behemoth" },
      { id: "UNIQUE_MOUNT_ENT_CRYSTAL", name: "Crystal Ent" },
      {
        id: "UNIQUE_MOUNT_BATTLESPIDER_CRYSTAL",
        name: "Crystal Battle Spider",
      },
      { id: "UNIQUE_MOUNT_BASTION_CRYSTAL", name: "Crystal Bastion" },
      { id: "UNIQUE_MOUNT_JUGGERNAUT_CRYSTAL", name: "Crystal Juggernaut" },
      { id: "UNIQUE_MOUNT_TANKBEETLE_CRYSTAL", name: "Crystal Tank Beetle" },
    ],
  },
  armor: {
    categories: [
      {
        name: "Cloth",
        image: "T3_ARMOR_CLOTH_SET1",
        items: [
          { id: "T8_ARMOR_CLOTH_SET1", name: "Scholar Robe" },
          { id: "T8_ARMOR_CLOTH_SET2", name: "Cleric Robe" },
          { id: "T8_ARMOR_CLOTH_SET3", name: "Mage Robe" },
          { id: "T8_ARMOR_CLOTH_ROYAL", name: "Royal Robe" },
          { id: "T8_ARMOR_CLOTH_KEEPER", name: "Druid Robe" },
          { id: "T8_ARMOR_CLOTH_HELL", name: "Fiend Robe" },
          { id: "T8_ARMOR_CLOTH_MORGANA", name: "Cultist Robe" },
          { id: "T8_ARMOR_CLOTH_FEY", name: "Feyscale Robe" },
          { id: "T8_ARMOR_CLOTH_AVALON", name: "Avalonian Robe" },
        ],
      },
      {
        name: "Leather",
        image: "T3_ARMOR_LEATHER_SET1",
        items: [
          { id: "T8_ARMOR_LEATHER_SET1", name: "Mercenary Jacket" },
          { id: "T8_ARMOR_LEATHER_SET2", name: "Hunter Jacket" },
          { id: "T8_ARMOR_LEATHER_SET3", name: "Assassin Jacket" },
          { id: "T8_ARMOR_LEATHER_ROYAL", name: "Royal Jacket" },
          { id: "T8_ARMOR_LEATHER_MORGANA", name: "Hellion Jacket" },
          { id: "T8_ARMOR_LEATHER_HELL", name: "Stalker Jacket" },
          { id: "T8_ARMOR_LEATHER_UNDEAD", name: "Specter Jacket" },
          { id: "T8_ARMOR_LEATHER_FEY", name: "Feyscale Jacket" },
          { id: "T8_ARMOR_LEATHER_AVALON", name: "Avalonian Jacket" },
        ],
      },
      {
        name: "Plate",
        image: "T3_ARMOR_PLATE_SET1",
        items: [
          { id: "T8_ARMOR_PLATE_SET1", name: "Soldier Armor" },
          { id: "T8_ARMOR_PLATE_SET2", name: "Knight Armor" },
          { id: "T8_ARMOR_PLATE_SET3", name: "Guardian Armor" },
          { id: "T8_ARMOR_PLATE_ROYAL", name: "Royal Armor" },
          { id: "T8_ARMOR_PLATE_UNDEAD", name: "Graveguard Armor" },
          { id: "T8_ARMOR_PLATE_HELL", name: "Demon Armor" },
          { id: "T8_ARMOR_PLATE_KEEPER", name: "Judicator Armor" },
          { id: "T8_ARMOR_PLATE_FEY", name: "Feyscale Armor" },
          { id: "T8_ARMOR_PLATE_AVALON", name: "Avalonian Armor" },
        ],
      },
    ],
  },

  right: {
    categories: [
      {
        name: "Book",
        image: "T3_OFF_BOOK",
        items: [
          { id: "T8_OFF_BOOK", name: "Tome of Spells" },
          { id: "T8_OFF_ORB_MORGANA", name: "Eye of secrets" },
          { id: "T8_OFF_DEMONSKULL_HELL", name: "Muisak" },
          { id: "T8_OFF_TOTEM_KEEPER", name: "Taproot" },
          { id: "T8_OFF_CENSER_AVALON", name: "Celestial Censer" },
        ],
      },
      {
        name: "Torch",
        image: "T3_OFF_TORCH",
        items: [
          { id: "T8_OFF_TORCH", name: "Torch" },
          { id: "T8_OFF_HORN_KEEPER", name: "Mistcaller" },
          { id: "T8_OFF_TALISMAN_AVALON", name: "Avalonian Talisman" },
          { id: "T8_OFF_LAMP_UNDEAD", name: "Ghastly Lamp" },
          { id: "T8_OFF_JESTERCANE_HELL", name: "Hellfire Cane" },
        ],
      },
      {
        name: "Shield",
        image: "T3_OFF_SHIELD",
        items: [
          { id: "T8_OFF_SHIELD", name: "Shield" },
          { id: "T8_OFF_TOWERSHIELD_UNDEAD", name: "Caitiff Shield" },
          { id: "T8_OFF_SHIELD_HELL", name: "Demon Shield" },
          { id: "T8_OFF_SPIKEDSHIELD_MORGANA", name: "Facebreaker" },
          { id: "T8_OFF_SHIELD_AVALON", name: "Avalonian Shield" },
        ],
      },
    ],
  },

  boots: {
    categories: [
      {
        name: "Boots",
        image: "T3_SHOES_CLOTH_SET1",
        items: [
          { id: "T8_SHOES_CLOTH_SET1", name: "Scholar Sandals" },
          { id: "T8_SHOES_CLOTH_SET2", name: "Cleric Sandals" },
          { id: "T8_SHOES_CLOTH_SET3", name: "Mage Sandals" },
          { id: "T8_SHOES_CLOTH_ROYAL", name: "Royal Sandals" },
          { id: "T8_SHOES_CLOTH_KEEPER", name: "Druid Sandals" },
          { id: "T8_SHOES_CLOTH_HELL", name: "Fiend Sandals" },
          { id: "T8_SHOES_CLOTH_MORGANA", name: "Cultist Sandals" },
          { id: "T8_SHOES_CLOTH_FEY", name: "Feyscale Sandals" },
          { id: "T8_SHOES_CLOTH_AVALON", name: "Avalonian Sandals" },
        ],
      },
      {
        name: "boots",
        image: "T3_SHOES_LEATHER_SET1",
        items: [
          { id: "T8_SHOES_LEATHER_SET1", name: "Hunter Shoes" },
          { id: "T8_SHOES_LEATHER_SET2", name: "Mercenary Shoes" },
          { id: "T8_SHOES_LEATHER_SET3", name: "Assassin Shoes" },
          { id: "T8_SHOES_LEATHER_ROYAL", name: "Royal Shoes" },
          { id: "T8_SHOES_LEATHER_MORGANA", name: "Specter Shoes" },
          { id: "T8_SHOES_LEATHER_UNDEAD", name: "Graveguard Boots" },
          { id: "T8_SHOES_LEATHER_HELL", name: "Hell" },

          { id: "T8_SHOES_LEATHER_FEY", name: "Feyscale Shoes" },
          { id: "T8_SHOES_LEATHER_AVALON", name: "Avalonian Shoes" },
        ],
      },
      {
        name: "boots",
        image: "T3_SHOES_PLATE_SET1",
        items: [
          { id: "T8_SHOES_PLATE_SET1", name: "Soldier Boots" },
          { id: "T8_SHOES_PLATE_SET2", name: "Knight Boots" },
          { id: "T8_SHOES_PLATE_SET3", name: "Guardian Boots" },
          { id: "T8_SHOES_PLATE_ROYAL", name: "Royal Boots" },
          { id: "T8_SHOES_PLATE_UNDEAD", name: "Graveguard Boots" },
          { id: "T8_SHOES_PLATE_HELL", name: "Demon Boots" },
          { id: "T8_SHOES_PLATE_KEEPER", name: "Judicator Boots" },
          { id: "T8_SHOES_PLATE_FEY", name: "Feyscale Boots" },
          { id: "T8_SHOES_PLATE_AVALON", name: "Avalonian Boots" },
        ],
      },
    ],
  },
  offhand: {
    categories: [
      {
        name: "Jednoruční meče",
        image: "T2_MAIN_FIRESTAFF",
        subcategories: [
          {
            name: "Krátké meče",
            image: "T3_MAIN_FIRESTAFF",
            items: [
              {
                id: "T8_MAIN_FIRESTAFF",
                twoHanded: false,
                name: "Scholar Cowl",
              },
              { id: "T8_2H_FIRESTAFF", twoHanded: true, name: "Scholar Cowl" },
              {
                id: "T8_2H_INFERNOSTAFF",
                twoHanded: true,
                name: "Scholar Cowl",
              },
              { id: "T8_MAIN_FIRESTAFF_KEEPER", twoHanded: false },
              { id: "T8_2H_FIRESTAFF_HELL", twoHanded: true },
              { id: "T8_2H_INFERNOSTAFF_MORGANA", twoHanded: true },
              { id: "T8_2H_FIRE_RINGPAIR_AVALON", twoHanded: true },
              { id: "T8_MAIN_FIRESTAFF_CRYSTAL", twoHanded: false },
            ],
          },
          {
            name: "Fighter Hoods",
            image: "T3_MAIN_HOLYSTAFF",
            items: [
              { id: "T8_MAIN_HOLYSTAFF", twoHanded: false },
              { id: "T8_2H_HOLYSTAFF", twoHanded: true },
              { id: "T8_2H_DIVINESTAFF", twoHanded: true },
              { id: "T8_MAIN_HOLYSTAFF_MORGANA", twoHanded: false },
              { id: "T8_2H_HOLYSTAFF_HELL", twoHanded: true },
              { id: "T8_2H_HOLYSTAFF_UNDEAD", twoHanded: true },
              { id: "T8_MAIN_HOLYSTAFF_AVALON", twoHanded: false },
              { id: "T8_2H_HOLYSTAFF_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Rapíry",
            image: "T3_MAIN_ARCANESTAFF",
            items: [
              { id: "T8_MAIN_ARCANESTAFF", twoHanded: false },
              { id: "T8_2H_ARCANESTAFF", twoHanded: true },
              { id: "T8_2H_ENIGMATICSTAFF", twoHanded: true },
              { id: "T8_MAIN_ARCANESTAFF_UNDEAD", twoHanded: false },
              { id: "T8_2H_ARCANESTAFF_HELL", twoHanded: true },
              { id: "T8_2H_ENIGMATICORB_MORGANA", twoHanded: true },
              { id: "T8_2H_ARCANE_RINGPAIR_AVALON", twoHanded: true },
              { id: "T8_2H_ARCANESTAFF_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Meče s efektem",
            image: "T3_MAIN_FROSTSTAFF",
            items: [
              { id: "T8_MAIN_FROSTSTAFF", twoHanded: false },
              { id: "T8_2H_FROSTSTAFF", twoHanded: true },
              { id: "T8_2H_GLACIALSTAFF", twoHanded: true },
              { id: "T8_MAIN_FROSTSTAFF_KEEPER", twoHanded: false },
              { id: "T8_2H_ICEGAUNTLETS_HELL", twoHanded: true },
              { id: "T8_2H_ICECRYSTAL_UNDEAD", twoHanded: true },
              { id: "T8_MAIN_FROSTSTAFF_AVALON", twoHanded: false },
              { id: "T8_2H_FROSTSTAFF_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Artefakty",
            image: "T3_MAIN_CURSEDSTAFF",
            items: [
              { id: "T8_MAIN_CURSEDSTAFF", twoHanded: false },
              { id: "T8_2H_CURSEDSTAFF", twoHanded: true },
              { id: "T8_2H_DEMONICSTAFF", twoHanded: true },
              { id: "T8_MAIN_CURSEDSTAFF_UNDEAD", twoHanded: false },
              { id: "T8_2H_SKULLORB_HELL", twoHanded: true },
              { id: "T8_2H_CURSEDSTAFF_MORGANA", twoHanded: true },
              { id: "T8_MAIN_CURSEDSTAFF_AVALON", twoHanded: false },
              { id: "T8_MAIN_CURSEDSTAFF_CRYSTAL", twoHanded: false },
            ],
          },
        ],
      },
      {
        name: "Magické off-handy",
        image: "T2_2H_BOW",
        subcategories: [
          {
            name: "Knihy",
            image: "T3_2H_BOW",
            items: [
              { id: "T8_2H_BOW", twoHanded: true },
              { id: "T8_2H_WARBOW", twoHanded: true },
              { id: "T8_2H_LONGBOW", twoHanded: true },
              { id: "T8_2H_LONGBOW_UNDEAD", twoHanded: true },
              { id: "T8_2H_BOW_HELL", twoHanded: true },
              { id: "T8_2H_BOW_KEEPER", twoHanded: true },
              { id: "T8_2H_BOW_AVALON", twoHanded: true },
              { id: "T8_2H_BOW_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Orby",
            image: "T3_MAIN_DAGGER",
            items: [
              { id: "T8_MAIN_DAGGER", twoHanded: false },
              { id: "T8_2H_DAGGERPAIR", twoHanded: true },
              { id: "T8_2H_CLAWPAIR", twoHanded: true },
              { id: "T8_MAIN_RAPIER_MORGANA", twoHanded: false },
              { id: "T8_MAIN_DAGGER_HELL", twoHanded: false },
              { id: "T8_2H_DUALSICKLE_UNDEAD", twoHanded: true },
              { id: "T8_2H_DAGGER_KATAR_AVALON", twoHanded: true },
              { id: "T8_2H_DAGGERPAIR_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Orby",
            image: "T3_MAIN_SPEAR",
            items: [
              { id: "T8_MAIN_SPEAR", twoHanded: false },
              { id: "T8_2H_SPEAR", twoHanded: true },
              { id: "T8_2H_GLAIVE", twoHanded: true },
              { id: "T8_MAIN_SPEAR_KEEPER", twoHanded: false },
              { id: "T8_2H_HARPOON_HELL", twoHanded: true },
              { id: "T8_2H_TRIDENT_UNDEAD", twoHanded: true },
              { id: "T8_MAIN_SPEAR_LANCE_AVALON", twoHanded: false },
              { id: "T8_2H_GLAIVE_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Orby",
            image: "T3_2H_QUARTERSTAFF",
            items: [
              { id: "T8_2H_QUARTERSTAFF", twoHanded: true },
              { id: "T8_2H_IRONCLADEDSTAFF", twoHanded: true },
              { id: "T8_2H_DOUBLEBLADEDSTAFF", twoHanded: true },
              { id: "T8_2H_COMBATSTAFF_MORGANA", twoHanded: true },
              { id: "T8_2H_TWINSCYTHE_HELL", twoHanded: true },
              { id: "T8_2H_ROCKSTAFF_KEEPER", twoHanded: true },
              { id: "T8_2H_QUARTERSTAFF_AVALON", twoHanded: true },
              { id: "T8_2H_DOUBLEBLADEDSTAFF_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Orby",
            image: "T8_2H_SHAPESHIFTER_SET1",
            items: [
              { id: "T8_2H_SHAPESHIFTER_SET1", twoHanded: true },
              { id: "T8_2H_SHAPESHIFTER_SET2", twoHanded: true },
              { id: "T8_2H_SHAPESHIFTER_SET3", twoHanded: true },
              { id: "T8_2H_SHAPESHIFTER_MORGANA", twoHanded: true },
              { id: "T8_2H_SHAPESHIFTER_HELL", twoHanded: true },
              { id: "T8_2H_SHAPESHIFTER_KEEPER", twoHanded: true },
              { id: "T8_2H_SHAPESHIFTER_AVALON", twoHanded: true },
              { id: "T8_2H_SHAPESHIFTER_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Orby",
            image: "T3_MAIN_NATURESTAFF",
            items: [
              { id: "T8_MAIN_NATURESTAFF", twoHanded: false },
              { id: "T8_2H_NATURESTAFF", twoHanded: true },
              { id: "T8_2H_WILDSTAFF", twoHanded: true },
              { id: "T8_MAIN_NATURESTAFF_KEEPER", twoHanded: false },
              { id: "T8_2H_NATURESTAFF_HELL", twoHanded: true },
              { id: "T8_2H_NATURESTAFF_KEEPER", twoHanded: true },
              { id: "T8_MAIN_NATURESTAFF_AVALON", twoHanded: false },
              { id: "T8_MAIN_NATURESTAFF_CRYSTAL", twoHanded: false },
            ],
          },
        ],
      },
      {
        name: "Dvouruční hole",
        image: "T2_MAIN_SWORD",
        subcategories: [
          {
            name: "Ohnivé hole",
            image: "T3_MAIN_SWORD",
            items: [
              { id: "T8_MAIN_SWORD", twoHanded: false },
              { id: "T8_2H_CLAYMORE", twoHanded: true },
              { id: "T8_2H_DUALSWORD", twoHanded: true },
              { id: "T8_MAIN_SCIMITAR_MORGANA", twoHanded: false },
              { id: "T8_2H_CLEAVER_HELL", twoHanded: true },
              { id: "T8_2H_DUALSCIMITAR_UNDEAD", twoHanded: true },
              { id: "T8_2H_CLAYMORE_AVALON", twoHanded: true },
              { id: "T8_MAIN_SWORD_CRYSTAL", twoHanded: false },
            ],
          },
          {
            name: "Přírodní hole",
            image: "T3_MAIN_AXE",
            items: [
              { id: "T8_MAIN_AXE", twoHanded: false },
              { id: "T8_2H_AXE", twoHanded: true },
              { id: "T8_2H_HALBERD", twoHanded: true },
              { id: "T8_2H_HALBERD_MORGANA", twoHanded: true },
              { id: "T8_2H_SCYTHE_HELL", twoHanded: true },
              { id: "T8_2H_DUALAXE_KEEPER", twoHanded: true },
              { id: "T8_2H_AXE_AVALON", twoHanded: true },
              { id: "T8_2H_SCYTHE_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Svaté hole",
            image: "T3_MAIN_MACE",
            items: [
              { id: "T8_MAIN_MACE", twoHanded: false },
              { id: "T8_2H_MACE", twoHanded: true },
              { id: "T8_2H_FLAIL", twoHanded: true },
              { id: "T8_MAIN_ROCKMACE_KEEPER", twoHanded: false },
              { id: "T8_MAIN_MACE_HELL", twoHanded: false },
              { id: "T8_2H_MACE_MORGANA", twoHanded: true },
              { id: "T8_2H_DUALMACE_AVALON", twoHanded: true },
              { id: "T8_MAIN_MACE_CRYSTAL", twoHanded: false },
            ],
          },
          {
            name: "Temné hole",
            image: "T3_MAIN_HAMMER",
            items: [
              { id: "T8_MAIN_HAMMER", twoHanded: false },
              { id: "T8_2H_POLEHAMMER", twoHanded: true },
              { id: "T8_2H_HAMMER", twoHanded: true },
              { id: "T8_2H_HAMMER_UNDEAD", twoHanded: true },
              { id: "T8_2H_DUALHAMMER_HELL", twoHanded: true },
              { id: "T8_2H_RAM_KEEPER", twoHanded: true },
              { id: "T8_2H_HAMMER_AVALON", twoHanded: true },
              { id: "T8_2H_HAMMER_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Artefakty",
            image: "T3_2H_KNUCKLES_SET1",
            items: [
              { id: "T8_2H_KNUCKLES_SET1", twoHanded: true },
              { id: "T8_2H_KNUCKLES_SET2", twoHanded: true },
              { id: "T8_2H_KNUCKLES_SET3", twoHanded: true },
              { id: "T8_2H_KNUCKLES_KEEPER", twoHanded: true },
              { id: "T8_2H_KNUCKLES_HELL", twoHanded: true },
              { id: "T8_2H_KNUCKLES_MORGANA", twoHanded: true },
              { id: "T8_2H_KNUCKLES_AVALON", twoHanded: true },
              { id: "T8_2H_KNUCKLES_CRYSTAL", twoHanded: true },
            ],
          },
          {
            name: "Artefakty",
            image: "T3_2H_CROSSBOW",
            items: [
              { id: "T8_2H_CROSSBOW", twoHanded: true },
              { id: "T8_2H_CROSSBOWLARGE", twoHanded: true },
              { id: "T8_MAIN_1HCROSSBOW", twoHanded: false },
              { id: "T8_2H_REPEATINGCROSSBOW_UNDEAD", twoHanded: true },
              { id: "T8_2H_DUALCROSSBOW_HELL", twoHanded: true },
              { id: "T8_2H_CROSSBOWLARGE_MORGANA", twoHanded: true },
              { id: "T8_2H_CROSSBOW_CANNON_AVALON", twoHanded: true },
              { id: "T8_2H_DUALCROSSBOW_CRYSTAL", twoHanded: true },
            ],
          },
        ],
      },
    ],
  },
};

export default gearOptions;
